

spring:
  datasource:
    url: jdbc:postgresql://localhost/customer
    username: postgres
    password: xminds
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092 #2181
    consumer:
      group-id: number-consumer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      concurrency: 1
server:
  port: 8080
application:
  properties:
    topic: random_number_topic